# -*- coding: utf-8 -*-
"""up1데이터처리.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEXfLJsnr4CJnw4fBhPe71AfBXJDdGDi
"""

pip uninstall keras

pip install keras

pip install keras --upgrade

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# 데이터 불러오기
data = pd.read_csv("/content/drive/MyDrive/BME/modified_data2.csv")

data.head()

"""**UPDRS1**"""

updrs1= data.copy()
updrs1=updrs1.drop(columns=['updrs_2', 'updrs_3', 'updrs_4'])
updrs1.head()

# CSV 파일로 저장
updrs1.to_csv('/content/drive/MyDrive/BME/updrs1.csv', index=False)  # index를 저장하지 않으려면 index=False로 설정

updrs1.head()

"""**UPDRS2**"""

updrs2= data.copy()
updrs2= updrs2.drop(columns=['updrs_1', 'updrs_3', 'updrs_4'])
updrs2.head()

updrs2=updrs2.dropna()
updrs2.shape

updrs2.to_csv('/content/drive/MyDrive/BME/updrs2.csv', index=False)

updrs3=data.copy()
updrs3 = updrs3.drop(columns=['updrs_2','updrs_1','updrs_4'])
updrs3.head()

updrs3=updrs3.dropna()
updrs3.shape

updrs3.to_csv('/content/drive/MyDrive/BME/updrs3.csv', index=False)

updrs4=data.copy()
updrs4 = updrs4.drop(columns=['updrs_2','updrs_3','updrs_1'])
updrs4.head()

updrs4=updrs4.dropna()
updrs4.shape

updrs4.to_csv('/content/drive/MyDrive/BME/updrs4.csv', index=False)